### ISSUE TITLE
Update to use latest 'Immediate Issuance' API response type 

### ISSUE THREAD

**Issue by ronaldtse** [riboseinc/digicert#127]
As notified by Clint there is a new response type called "Immediate Issuance" for the "Request Certificate" endpoint.

Documentation here:
* [HTML](https://www.digicert.com/certcentral-support/immediate-certificate-issuance-feature.htm)
* [PDF](https://www.digicert.com/certcentral-support/immediate-certificate-issuance-guide-2017-09-21.pdf)

Clint: 
> If requests.status is “approved”, there should be two additional properties: `certificate_id` and `certificate_chain`. If there is an issue with the CA returning the certificate, it’s possible only the `certificate_id` will be returned. However, this also obsoletes the need to use the `requests.id` or `id` properties as you can now call the download endpoint directly using this `certificate_id`.

> The additional response properties applies for SSL certs, including new orders, renewals, reissues, and duplicates.

Looks like it's time for a new version!

**Comment by ronaldtse** [comment]
@abunashir So should we close this?

**Comment by abunashir** [comment]
@ronaldtse: Yes, I think we are good here :)

**Comment by MukilanP** [comment]
How do you verify that immediate issuance is working?. Do you have any sample to generate request token?

**Comment by abunashir** [comment]
Hey @MukilanP - the easy way to tell if the immediate issuance is working or not by looking at the response, for immediate one the `certificate_chain` is present and otherwise it is omitted. Here are some more details from the Digicert doc - [Certificate Immediate Issuance Doc](https://dev.digicert.com/en/certcentral-apis/services-api/workflows/ov-ev-certificate-immediate-issuance.html#what-if-digicert-can-t-immediately-issue-the-certificate--323543)

//cc: @ronaldtse
